apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor
spec:
  selector:
    matchLabels:
      app: skin-doctor
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: skin-doctor
        tier: frontend
        team: ai-platform
      annotations:
        babylonhealth/data-scientist: rfdickerson
    spec:
      containers:
      - name: image-service
        image: gcr.io/learn-kube-344502/image-service:v2
        command: ["uvicorn"]
        args: ["grpc_client:app", "--host", "0.0.0.0"]
        env:
          - name: TRITON_URL
            valueFrom:
              configMapKeyRef:
                name: skin-config
                key: triton.url
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

