apiVersion: v1
kind: Service
metadata:
  name: skin-doctor
spec:
  type: NodePort
  selector:
    app: skin-doctor
    tier: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
