apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: triton-monitor
spec:
  selector:
    matchLabels:
      app: triton-service
  endpoints:
  - port: metrics
    interval: 30s