apiVersion: v1
kind: Service
metadata:
  name: triton-service
spec:
  type: ClusterIP
  selector:
      app: triton
      tier: inference
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: grpc
      port: 8001
      targetPort: 8001
    - protocol: TCP
      name: metrics
      port: 8002
      targetPort: 8002
  
