apiVersion: v1
kind: Service
metadata:
  name: skin-doctor
  labels:
    app: skin-doctor
spec:
  type: NodePort
  selector:
    app: skin-doctor
    environment: production
  ports:
    - protocol: TCP
      port: 8000
